site_name: San-Ren 的自留地
site_url: https://yourname.github.io/private-plot/
repo_url: https://github.com/san-ren/private-plot
repo_name: san-ren/private-plot
edit_uri: edit/main/docs/

# 这里的配置实现了“沉浸式”布局
theme:
  name: material             # 必须是 material
  language: zh
  features:
    - navigation.tabs        # 【关键】顶部导航栏
    - navigation.tabs.sticky # 导航栏吸顶
    - navigation.sections    # 侧边栏保持分类
    - navigation.expand      # 默认展开
    - navigation.top         # 返回顶部按钮
    # - toc.integrate          # 【关键】将右侧目录合并到左侧
    - search.suggest         # 搜索建议
    - content.code.copy      # 复制代码按钮
  palette: 
    - scheme: slate          # 【关键】深色模式
      primary: black         # 顶栏全黑
      accent: indigo         # 强调色
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式
    - scheme: default        # 亮色模式
      primary: white         # 顶栏全白（类似苹果官网）
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式


extra_css:
  - stylesheets/extra.css

use_directory_urls: false


plugins:
  - search
  - awesome-pages
  - document-dates:
      position: top            # 显示位置: top(标题后) bottom(文档末尾), 默认: top
      type: date               # 日期类型: date datetime timeago, 默认: date
      exclude:                 # 排除文件列表
        - temp.md                  # 示例：排除指定文件
        - blog/*                   # 示例：排除 blog 目录下所有文件，包括子目录
      date_format: '%Y-%m-%d'  # 日期格式化字符串（例如: %Y年%m月%d日、%b %d, %Y）
      time_format: '%H:%M:%S'  # 时间格式化字符串（仅在 type=datetime 时有效）
      show_created: true       # 显示创建日期: true false, 默认: true
      show_updated: true       # 显示最后更新日期: true false, 默认: true
      show_author: true        # 显示作者: true(头像) text(文本) false(隐藏), 默认: true
  - callouts   # 兼容GitHub提示框（> [!WARNING]），安装的是 `mkdocs-callouts` (这是一个 MkDocs 的插件)。


markdown_extensions:

  - admonition            # 提示块(支持 !!! 语法)
  - pymdownx.details      # 折叠块
  - pymdownx.highlight:   # 代码高亮
      anchor_linenums: true
  - pymdownx.superfences  # 代码块嵌套
  - pymdownx.tabbed:      # 选项卡
      alternate_style: true 
  - toc:
      permalink: true     
  - pymdownx.tilde        # 删除线 ~~text~~
  - pymdownx.tasklist:    # 任务列表 - [ ]
      custom_checkbox: true
  - pymdownx.magiclink    # 自动识别链接

 